apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: daily-getallprojects
spec:
  schedule: "00 00 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: daily-getallprojects
            image: appropriate/curl
            args:
            - /bin/sh
            - -c
            - curl https://us-central1-fir-oss.cloudfunctions.net/getAllProjects
          restartPolicy: OnFailure